# Generated by Django 3.2.7 on 2021-11-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='start_date',
            new_name='date_created',
        ),
    ]
