# Generated by Django 3.2.7 on 2021-10-28 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='author',
        ),
        migrations.AddField(
            model_name='election',
            name='election_admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
