# Generated by Django 3.2.7 on 2021-10-28 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0002_auto_20211028_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='election_admins',
        ),
        migrations.AddField(
            model_name='election',
            name='admins',
            field=models.ManyToManyField(related_name='election_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(related_name='election_voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='election_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
