# Generated by Django 3.2.7 on 2021-10-28 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0004_auto_20211028_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_details',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='election_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
