# Generated by Django 3.2.7 on 2021-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20211028_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
