# Generated by Django 3.2.7 on 2021-10-28 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0007_auto_20211028_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='election_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='election_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
