# Generated by Django 3.2.7 on 2021-10-29 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20211028_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='has_ended',
        ),
        migrations.RemoveField(
            model_name='election',
            name='has_started',
        ),
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
