# Generated by Django 3.2.7 on 2021-10-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20211029_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='vote',
            new_name='vote_details',
        ),
    ]
