# Generated by Django 3.2.7 on 2021-10-30 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0010_rename_vote_ballot_vote_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voted_voters',
            field=models.ManyToManyField(blank=True, related_name='election_voted_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
